-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 15:28:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database projet3_lunetic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Database projet3_lunetic
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `projet3_lunetic` DEFAULT CHARACTER SET utf8 ;
USE `projet3_lunetic` ;

-- -----------------------------------------------------
-- Table `projet3_lunetic`.`opticians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`opticians` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`opticians` (
  `id_optician` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `other_address` VARCHAR(255) NULL,
  `postal_code` VARCHAR(50) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `mobile_phone` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NULL,
  `website` VARCHAR(255) NULL,
  `home_phone` VARCHAR(50) NULL,
  `finess_code` VARCHAR(20) NULL,
  `siret` VARCHAR(25) NULL,
  `vat_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id_optician`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`collections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`collections` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`collections` (
  `id_collection` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_collection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`models` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`models` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_collection` INT NOT NULL,
  PRIMARY KEY (`id_model`),
  INDEX `id_collection_idx` (`id_collection` ASC) VISIBLE,
  CONSTRAINT `id_collection`
    FOREIGN KEY (`id_collection`)
    REFERENCES `projet3_lunetic`.`collections` (`id_collection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`colors` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`colors` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`models_colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`models_colors` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`models_colors` (
  `id_model_color` INT NOT NULL AUTO_INCREMENT,
  `id_color` INT NULL,
  `id_model` INT NULL,
  PRIMARY KEY (`id_model_color`),
  INDEX `id_colors_idx` (`id_color` ASC) VISIBLE,
  INDEX `id_models_idx` (`id_model` ASC) VISIBLE,
  CONSTRAINT `id_color`
    FOREIGN KEY (`id_color`)
    REFERENCES `projet3_lunetic`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_model`
    FOREIGN KEY (`id_model`)
    REFERENCES `projet3_lunetic`.`models` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`wishlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`wishlists` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`wishlists` (
  `id_wishlist` INT NOT NULL AUTO_INCREMENT,
  `id_optician` INT NULL,
  `date` DATETIME NULL,
  `name` VARCHAR(255) NOT NULL,
  `id_model_color` INT NOT NULL,
  PRIMARY KEY (`id_wishlist`),
  INDEX `id_optician_idx` (`id_optician` ASC) VISIBLE,
  INDEX `id_model_color_idx` (`id_model_color` ASC) VISIBLE,
  CONSTRAINT `id_optician`
    FOREIGN KEY (`id_optician`)
    REFERENCES `projet3_lunetic`.`opticians` (`id_optician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_model_color`
    FOREIGN KEY (`id_model_color`)
    REFERENCES `projet3_lunetic`.`models_colors` (`id_model_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`branches` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`branches` (
  `id_branch` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_color` INT NOT NULL,
  PRIMARY KEY (`id_branch`),
  INDEX `id_color_idx` (`id_color` ASC) VISIBLE,
  CONSTRAINT `id_color`
    FOREIGN KEY (`id_color`)
    REFERENCES `projet3_lunetic`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`models_branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`models_branches` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`models_branches` (
  `id_models_branches` INT NOT NULL AUTO_INCREMENT,
  `id_model` INT NOT NULL,
  `id_branch` INT NOT NULL,
  PRIMARY KEY (`id_models_branches`),
  INDEX `id_model_idx` (`id_model` ASC) VISIBLE,
  INDEX `id_branch_idx` (`id_branch` ASC) VISIBLE,
  CONSTRAINT `id_model`
    FOREIGN KEY (`id_model`)
    REFERENCES `projet3_lunetic`.`models` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_branch`
    FOREIGN KEY (`id_branch`)
    REFERENCES `projet3_lunetic`.`branches` (`id_branch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet3_lunetic`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet3_lunetic`.`orders` ;

CREATE TABLE IF NOT EXISTS `projet3_lunetic`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL,
  `id_optician` INT NOT NULL,
  `date` DATE NOT NULL,
  `link_pdf` VARCHAR(255) NULL,
  PRIMARY KEY (`id_order`),
  INDEX `id_optician_idx` (`id_optician` ASC) VISIBLE,
  CONSTRAINT `id_optician`
    FOREIGN KEY (`id_optician`)
    REFERENCES `projet3_lunetic`.`opticians` (`id_optician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
